### Create new Sensor data
POST http://localhost:8080/api/sensor-data
Content-Type: application/json

{
  "temperature": 21.7,
  "humidity": 47.5,
  "pressure": 1023.8,
  "co2": 513.9
}

### Find aLl Sensor data
GET http://localhost:8080/api/sensor-data

### Find Sensor data by ID
GET http://localhost:8080/api/sensor-data/2

### Update an existing Sensor data
PUT http://localhost:8080/api/sensor-data/1
Content-Type: application/json

{
  "id": 1,
  "temperature": 24.7,
  "humidity": 49.5,
  "pressure": 1021.8,
  "co2": 613.9
}

### Delete a Sensor data
DELETE http://localhost:8080/api/sensor-data/1